package com.example.rickandmortywiki.services.models.mockData

import com.example.rickandmortywiki.R
import com.example.rickandmortywiki.services.models.CharacterModel
import com.example.rickandmortywiki.services.models.components.CharacterLocationModel
import com.example.rickandmortywiki.services.models.components.EpisodeUrlModel
import com.example.rickandmortywiki.services.models.components.CharacterOriginModel

object MockCharacterData {
    val charactersList = listOf<CharacterModel>(
        //region Personagem 1 - Rick Sanchez
        CharacterModel(
            id = 1,
            name = "Rick Sanchez",
            status = "Alive",
            species = "Human",
            type = "",
            gender = "Male",
            origin = CharacterOriginModel(
                name = "Earth (C-137)",
                url = "https://rickandmortyapi.com/api/location/1"
            ),
            location = CharacterLocationModel(
                name = "Citadel of Ricks",
                url = "https://rickandmortyapi.com/api/location/3",
            ),
            image = R.drawable.rick_sanchez,
            episode = listOf(
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/1"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/2"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/3"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/4"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/5"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/6"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/7"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/8"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/9"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/10"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/11"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/12"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/13"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/14"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/15"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/16"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/17"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/18"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/19"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/20"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/21"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/22"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/23"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/24"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/25"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/26"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/27"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/28"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/29"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/30"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/31"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/32"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/33"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/34"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/35"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/36"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/37"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/38"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/39"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/40"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/41"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/42"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/43"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/44"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/45"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/46"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/47"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/48"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/49"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/50"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/51")
            ),
            url = "https://rickandmortyapi.com/api/character/1",
            created = "2017-11-04T18:48:46.250Z"
        ),
        //endregion
        //region Personagem 2 - Morty Smith
        CharacterModel(
            id = 2,
            name = "Morty Smith",
            status = "Alive",
            species = "Human",
            type = "",
            gender = "Male",
            origin = CharacterOriginModel(
                name = "unknown",
                url = ""
            ),
            location = CharacterLocationModel(
                name = "Citadel of Ricks",
                url = "https://rickandmortyapi.com/api/location/3"
            ),
            image = R.drawable.morty_smith,
            episode = listOf(
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/1"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/2"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/3"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/4"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/5"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/6"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/7"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/8"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/9"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/10"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/11"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/12"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/13"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/14"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/15"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/16"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/17"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/18"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/19"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/20"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/21"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/22"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/23"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/24"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/25"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/26"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/27"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/28"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/29"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/30"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/31"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/32"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/33"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/34"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/35"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/36"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/37"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/38"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/39"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/40"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/41"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/42"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/43"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/44"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/45"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/46"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/47"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/48"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/49"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/50"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/51")
            ),
            url = "https://rickandmortyapi.com/api/character/2",
            created = "2017-11-04T18:50:21.651Z"
        ),
        //endregion
        //region Personagem 3 - Summer Smith
        CharacterModel(
            id = 3,
            name = "Summer Smith",
            status = "Alive",
            species = "Human",
            type = "",
            gender = "Female",
            origin = CharacterOriginModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            location = CharacterLocationModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            image = R.drawable.summer_smith,
            episode = listOf(
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/6"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/7"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/8"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/9"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/10"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/11"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/12"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/14"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/15"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/16"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/17"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/18"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/19"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/20"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/21"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/22"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/23"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/24"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/25"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/26"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/27"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/29"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/30"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/31"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/32"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/33"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/34"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/35"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/36"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/38"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/39"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/40"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/41"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/42"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/43"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/44"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/45"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/46"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/47"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/48"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/49"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/51")
            ),
            url = "https://rickandmortyapi.com/api/character/3",
            created = "2017-11-04T19:09:56.428Z"
        ),
        //endregion
        //region Personagem 4 - Beth Smith
        CharacterModel(
            id = 4,
            name = "Beth Smith",
            status = "Alive",
            species = "Human",
            type = "",
            gender = "Female",
            origin = CharacterOriginModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            location = CharacterLocationModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            image = R.drawable.beth_smith,
            episode = listOf(
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/6"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/7"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/8"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/9"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/10"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/11"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/12"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/14"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/15"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/16"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/18"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/19"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/20"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/21"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/22"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/23"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/24"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/25"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/26"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/27"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/28"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/29"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/30"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/31"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/32"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/33"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/34"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/35"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/36"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/38"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/39"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/40"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/41"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/42"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/43"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/44"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/45"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/46"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/47"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/48"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/49"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/51")
            ),
            url = "https://rickandmortyapi.com/api/character/4",
            created = "2017-11-04T19:22:43.665Z"
        ),
        //endregion
        //region Personagem 5 - Jerry Smith
        CharacterModel(
            id = 5,
            name = "Jerry Smith",
            status = "Alive",
            species = "Human",
            type = "",
            gender = "Male",
            origin = CharacterOriginModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            location = CharacterLocationModel(
                name = "Earth (Replacement Dimension)",
                url = "https://rickandmortyapi.com/api/location/20"
            ),
            image = R.drawable.jerry_smith,
            episode = listOf(
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/6"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/7"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/8"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/9"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/10"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/11"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/12"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/13"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/14"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/15"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/16"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/18"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/19"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/20"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/21"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/22"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/23"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/26"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/29"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/30"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/31"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/32"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/33"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/35"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/36"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/38"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/39"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/40"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/41"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/42"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/43"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/44"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/45"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/46"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/47"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/48"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/49"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/50"),
                EpisodeUrlModel("https://rickandmortyapi.com/api/episode/51")
            ),
            url = "https://rickandmortyapi.com/api/character/5",
            created = "2017-11-04T19:26:56.301Z"
        )
        //endregion
    )

    fun getCharacterById(characterId: Int?): CharacterModel {
        return charactersList.first { it.id == characterId }
    }
}